# Generated by Django 3.0.2 on 2020-03-23 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviews', models.TextField()),
                ('ratings', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
